# Generated by Django 3.2.8 on 2021-10-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobSkills',
            new_name='JobSkill',
        ),
    ]
